config/routes.rb
Rails.application.routes.draw do
  get 'maps/index'
  devise_for :users
  root to: 'heritages#index'
  resources :heritages, only: [:new, :create, :show, :edit, :update, :destroy] do
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :maps, only: :index
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heritage.rb
class Heritage < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :image

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true  
  validates :image, presence: true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          has_many :heritages

        with_options presence: true do
        validates :nickname
        validates :profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/heritages_controller.rb
class HeritagesController < ApplicationController
  before_action :set_heritage, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @heritages = Heritage.includes(:user)
  end

  def new
    @heritage = Heritage.new
  end

  def create
      @heritage = Heritage.new(heritage_params)
      if @heritage.save
        redirect_to root_path
      else
        render :new
      end
    end

    def destroy
      heritage = Heritage.find(params[:id])
      heritage.destroy
    end

    def edit
    end

    def update
      heritage = Heritage.find(params[:id])
      heritage.update(heritage_params)
    end
  
    def show
      
    end

  private

  def heritage_params
    params.require(:heritage).permit(:title, :image, :catch_copy, :concept).merge(user_id: current_user.id)
  end

  def set_heritage
    @heritage = Heritage.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @heritage.user
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @heritages = current_user.heritages
    @profile = current_user.profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heritages_helper.rb
module HeritagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/heritages/_heritage.html.erb
 <div class="content_post" style="background-image: <%= link_to image_tag(heritage.image,class: "content_post"), heritage_path(heritage) if heritage.image.attached?%>;">
     <div class="more">
     <% if user_signed_in? && current_user.id == heritage.user_id %>
        <span><h3>…</h3></span>
        <ul class="more_list">
        <li>
            <%= link_to '詳細', heritage_path(heritage.id), method: :get %>
          </li>
          
        <li>
            <%= link_to '編集', edit_heritage_path(heritage.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', heritage_path(heritage.id), method: :delete %>
          </li>
          <% end %>
        </ul>
      </div>
      <p><%= heritage.title %></p>
      <% if user_signed_in? %>
      <span class="name">
      <a href="/users/<%= heritage.user.id %>">
          <span>投稿者</span><%= heritage.user.nickname %>
          <% end %>
          
        </a>
      </span>
    </div>

app/views/heritages/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/heritages/destroy.html.erb
<div class = "destroy">
  <div class="contents row">
    <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/heritages/edit.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">世界遺産view</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a><%=link_to 'トップページ', root_path, class:"nav-link active" %></a>
        </ul>
      </div>
    </div>
  </div>
  </nav>
</header>
  <div class= "edit">
    <div class="contents row">
      <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @heritage, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "タイトル" %>
      <%= form.file_field :image, placeholder: "写真を選択" %>
      <%= form.text_field :catch_copy, placeholder: "キャッチコピー" %>
      <%= form.text_area :concept, placeholder: "コメント", rows: "10" %>
      <%= form.submit "変更", class: :edit__btn %>
    <% end %>
    </div>
  </div>
</div>

app/views/heritages/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">世界遺産view</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg  class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        <%= image_tag "/assets/japan_mix.jpeg", class:"bd-placeholder-img" %>
        <div class="container">
          <div class="carousel-caption text-start">
          <% if user_signed_in? %>
          <h1>ようこそ！<%= "#{current_user.nickname}さん" %></h1>
            <p><%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-lg btn-primary" %></p>
            </div>
          <% else %>
          <h1> ユーザー登録しよう！ </h1>
            <p><%= link_to '新規登録', new_user_registration_path, class: "btn btn-lg btn-primary" %></p>
            <p><%= link_to 'ログイン', new_user_session_path, class: "btn btn-lg btn-primary" %></p>
          </div>
          <% end %>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
          <%= image_tag "/assets/Kyoto_World_Heritage.jpeg", class:"bd-placeholder-img" %>
        <div class="container">
          <div class="carousel-caption">
          <% if user_signed_in? %>
            <h1>世界遺産を探す</h1>
            <p><%= link_to 'MAP', maps_path, class: "btn btn-lg btn-primary" %></p>
            <% else %>
            <h1>世界遺産</h1>
            <% end %>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        <%= image_tag "/assets/sekaiisan_mv.jpeg", class:"bd-placeholder-img" %>
        <div class="container">
          <div class="carousel-caption text-end">
          <% if user_signed_in? %>
            <h1>投稿しよう！</h1>
            <p><%= link_to '投稿',new_heritage_path, class: "btn btn-lg btn-primary" %></p>
             <% else %>
             <h1>世界遺産</h1>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  


    <!-- START THE FEATURETTES -->

    
    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

<div class="contents row">
<h2> 投稿一覧 </h2>
  <% @heritages.each do |heritage| %>
     <%= render partial: "heritage", locals: { heritage: heritage } %>
  <% end %>
  </div>
</div>
<%= link_to(new_heritage_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag '富士山の無料アイコン.png' , size: '185x50' ,class: "purchase-btn-icon" %>

<% end %>
  <!-- FOOTER -->
  <footer class="footer">
    <p><a href="#">↑top</a></p>
  </footer>
</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

app/views/heritages/new.html.erb
<div class="contents row">
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">世界遺産view</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a><%=link_to 'トップページ', root_path, class:"nav-link active" %></a>
        </ul>
      </div>
    </div>
  </div>
  </nav>
</header>
  <div class="container">
    <h3>世界遺産</h3>
    <%= form_with(model: @heritage, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "タイトル" %>
      <%= form.file_field :image, placeholder: "写真を選択" %>
      <%= form.text_field :catch_copy, placeholder: "キャッチコピー" %>
      <%= form.text_area :concept, placeholder: "コメント", rows: "10" %>
      <%= form.submit "投稿", class: :form__btn %>
    <% end %>
  </div>
</div>

app/views/heritages/show.html.erb
<main class="main">
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">世界遺産view</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a><%=link_to 'トップページ', root_path, class:"nav-link active" %></a>
        </ul>
      </div>
    </div>
  </div>
  </nav>
</header>
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @heritage.title %>
        <div class = "heritage__user">
      </p>
     <% @heritage.user.nickname %>
      <% if current_user == @heritage.user%>
      </div>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_heritage_path(@heritage), class: :prototype__btn %>
          <%= link_to "削除する", heritage_path(@heritage), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="heritage__image">
        <%= image_tag @heritage.image %>
      </div>
      <div class="_body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @heritage.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @heritage.concept %>
          </p>
        </div>
      </div>
      </div>
    </div>
  </div>
</main>

app/views/heritages/update.html.erb
<div class="update">
  <div class="contents row">
    <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>世界遺産view</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">世界遺産view</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a><%=link_to 'トップページ', root_path, class:"nav-link active" %></a>
        </ul>
      </div>
    </div>
  </div>
  </nav>
</header>

<div class="contents row">
<div class ="mypage">
<h4><%= @user.nickname %>さんのマイページ</h4>
<h5>[プロフィール]</h5>
  <p class="plofile"><%= @user.profile %> </p>
  </div>
 <%= render partial: 'heritages/heritage', collection: @user.heritages %>
    </div>
  </div>
</div>